### ISSUE TITLE
[Discussion] NetlifyCMS Starter Listings (Official vs Community)

### ISSUE THREAD

**Issue by talves** [decaporg/decap-cms#1897]
A community member for a specific project like "Middleman" gets created by a community member. Later the Middleman project comes out with their **"Official"** starter and wants theirs to be the starter listed.

Listings of starters is good for NetlifyCMS and the targeted starter projects.

Discussion Items:

- How to differentiate an Official starter from a Community member starter
- Do we have a separation in the list on the docs page for Project vs Contributor (Official vs Community)?
- Do we just leave it alone as it is and publish all starters created by community members. Maybe flag the official starters.
- What makes a starter **Official**? If it is maintained actively in the same org/user section of git?

Copyright on logos is also something to think about, but in most cases the project can always make a PR for logo fixes.

reference: #1895

**Comment by erquhart** [comment]
We don't really have a starter listing right now for the CMS, but we should, agreed. The example projects page isn't a great place for it, a bit out of the way. But maybe there or a duplicate of it called Starters?

We can swap out which starters are featured on the Start With a Template page at will as long as we have a canonical list, which I think is your point.

Thoughts on your discussion items:
> How to differentiate an Official starter from a Community member starter
I honestly don't think we need to.

> Do we have a separation in the list on the docs page for Project vs Contributor (Official vs Community)?
Don't think we need to, but can you confirm which page you're thinking of?

> Do we just leave it alone as it is and publish all starters created by community members. Maybe flag the official starters.
Agreed.

> What makes a starter Official? If it is maintained actively in the same org/user section of git?
That's the thing, I'm really not sure there's much of a difference. We do keep an eye on them, check issues/PR's, etc for quality control, but community help is needed for them to really thrive (example: @ZoltanVeres' recent work on the Gatsby starter repo)

By "official" are you thinking mostly of those that are on the Start with a Template page?

**Comment by tomrutgers** [comment]
> How to differentiate an Official starter from a Community member starter

I think it would make a bit of sense to make a difference. Agreed, we do need community help to set these starters up and maintain them, but there is a difference in perception: Using something that is backed by a big community / organization vs. some repo that a random dude put together (like my middleman starter which has a very impressive count of 3 stars on github). 

> Maybe flag the official starters.

This feels like an elegant solution

I think there should also be some requirements for a starter to be a starter, so users can compare the starters a bit better, if that makes sense. We can put a 'Add to Netlify' button in pretty much every readme and call it a starter, but that doesn't say anything about the quality of the actual product. That would also make it easier to get started on making one, since there would be guidelines you can follow.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
