### ISSUE TITLE
netlify-cms-core react dependency

### ISSUE THREAD

**Issue by boombang** [decaporg/decap-cms#2673]
**Describe the bug**
According to https://www.netlifycms.org/blog/2019/07/netlify-cms-gatsby-plugin-4-0-0/ instead of netlify-cms we need to use netlify-cms-app package as it has React as a peer dependency. But netlify-cms-app also has netlify-cms-core dependency https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-app/package.json#L33 which has React as a dependency, not a peer one https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/package.json#L39
Because of that I still have multiple instances of React.

**Expected behavior**
In the package.json of netlify-cms-core react is set as a peer dependency

**Screenshots**
![image](https://user-images.githubusercontent.com/12898065/64686695-bd225100-d491-11e9-818d-a1e8636be80a.png)

**Comment by talves** [comment]
@boombang Great catch, but luckily is is also specified in the peer dependencies, so the bundler picks it up during the build process and ignores the dependency and treats it as an external. Are you seeing an error for a duplicate React instance otherwise?

If you want, you can submit a quick PR with the dependency removed. Thanks.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
