### ISSUE TITLE
API exposing entry and collection data

### ISSUE THREAD

**Issue by vai0** [decaporg/decap-cms#3246]
The problem I'm encountering ATM is an entry is not erroring when it has the same identifier field as another entry in the same collection. https://github.com/netlify/netlify-cms/issues/2829

As a potential workaround to this problem I see there exists the ability to "hook" into prepublish events with [`CMS.registerEventListener`](https://github.com/netlify/netlify-cms/blob/master/website/content/docs/beta-features.md#registering-to-cms-events).

What I'd like to try is on pre-publish, fetch for all the identifier values in the same collection and match that against the currently published entry's identifier value. If there exists a match, somehow throw an error and prevent the publish.

But to do this - I need to know:
- the identifier value of the entry
- the identifier values of all entries in the same collection

1. Are there any API's that CMS exposes that can allow me to get this info? 
2. Is there an API that allows me to throw toast notification errors similar to what field validation errors throw?

**Comment by saschatu** [comment]
HI @vai0,
since netlify CMS does not has its own persistancy you can use the API of the repository where the data is stored (e.g. GitHub). OR you get the API through other tools you maybe use anyways for buildign your website - e.g. gridsome, which loads the netlfiy CMS data (by parsing the files) and exposes a GraphQL to browse the data. 
BR
Sascha

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
