### ISSUE TITLE
Default values for hidden widgets need to be updated

### ISSUE THREAD

**Issue by madsem** [decaporg/decap-cms#5613]
**Is your feature request related to a problem? Please describe.**
Currently the `hidden` widget does not update values set as `default`.
They are created once, but then never update even if they were accidentally changed through other means, like a find & replace in developers IDE.

The hidden fields are not even part of the form when updating existing content... (As far as I can tell)

This is unexpected behavior imho. These fields should always be updated with their default value.

Imagine this:
```js
fields: [
    {
      label: "Meta Robots Tag",
      name: "robots",
      widget: "hidden",
      default: "all",
    }
]
```

On creation this is set to "all', as expected.

Now since we're working with static sites, often developers or even authors work in their IDE using `find/replace`.
It's very easy for a default value to change without realizing it.

So if the `robots` value changes on accident, it will never change again even if the content is updated through the CMS.
```js
fields: [
    {
      label: "Meta Robots Tag",
      name: "robots",
      widget: "hidden",
      default: "noindex,nofollow",
    }
]
```
If this was changed for example through an erroneous find/replace, it would not ever be updated again, unless you spot the issue and update it manually.
 
Or another scenario... a default value for a hidden widget changes. It should be possible to update content through the UI, knowing the content will have the new default values. 

**Describe the solution you'd like**
`hidden` widgets should always be part of the CMS form, also for existing content, and update / overwrite old values.
That is why they are hidden and have a default value.

**Comment by erezrokah** [comment]
Hi @madsem, can you follow the feature request template https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title or the bug report template https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title?

I'm not sure if you're reporting a bug or a feature, and what is the expected behavior you'd like to have.

I think it's expected that the hidden widget is not shown in the UI:
https://www.netlifycms.org/docs/widgets/#hidden

**Comment by madsem** [comment]
@erezrokah I've updated it.
I wasn't talking about making `hidden` widgets visible, I was talking about the fact that they aren't updating their default values.
