### ISSUE TITLE
Update code blocks in Extending Widgets doc

### ISSUE THREAD

**Issue by verythorough** [decaporg/decap-cms#571]
**- Do you want to request a *feature* or report a *bug*?**
docs update

**- What is the current behavior?**
The sample code blocks for `registerWidget` and `registerEditorComponent` use the `createClass` pattern, rather than the currently more common methods using JSX.

**- What is the expected behavior?**
Writing these with more common modern patterns will make them easier for new users to interpret and modify.

This could be a good opportunity for someone who knows React and is looking for a bite-sized initial contribution. Otherwise, @bdougie has volunteered to take it on.

**Comment by verythorough** [comment]
Also worth noting, [this line](https://github.com/netlify/netlify-cms/blame/master/docs/extending.md#L88) includes an invalid regex string. It should look more like [this line](https://github.com/netlify/netlify-cms/blob/master/src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec.js#L30). And incidentally, the code in that file can serve as a model when updating the code samples.

**Comment by erquhart** [comment]
@verythorough JSX requires transpiling that may not be present at the point of CMS customization, e.g. inline scripts in the CMS HTML. We're also providing the `createClass` and `h` (alias for `createElement`) functions in the global scope so that custom widgets can hook into React without requiring it separately.

I do think it'd be good to provide additional examples that depict usage within separate scripts, including importing React and using JSX to create components.

**Comment by verythorough** [comment]
Ah, thanks for explaining the logic there. I think we'll need to provide more explanation, then, because models for "riffing" on the example are difficult to find. Built-in widgets use a different syntax, and while I see the convenience of the `h` alias, it's not very searchable.

**Comment by tech4him1** [comment]
Related to #588.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
