### ISSUE TITLE
Hi. Error  "No Entries"

### ISSUE THREAD

**Issue by snagovskiy** [decaporg/decap-cms#6807]
cms does not work with this version <script src="https://unpkg.com/netlify-cms @^0.7.0/dist/cms.js "></script>.
does not see the files of the posts of pages, images, files in _data/the interface itself is loaded.
everything works with this version, but <script src=" works with this onehttps://unpkg.com/netlify-cms @^2.0.0/dist/netlify-cms.js "></script>
collections:
  - name: "post"
    label: "Posts"
    folder: "_posts"
    editor:

**Comment by martinjagodic** [comment]
I'm closing this as it is a question rather than an issue. If you need more help, please start a [discussion](https://github.com/decaporg/decap-cms/discussions/new/choose) or join us on [Discord](https://decapcms.org/chat). As you do that, explain your problem in greater detail. It's hard to make sense of your problem right now.
